---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kuard
  name: kuard
  namespace: demo
spec:
  containers:
    # you can simply reference gcr.io/kuar-demo/kuard-amd64:blue.
    # You can then demonstrate an upgrade with gcr.io/kuar-demo/kuard-amd64:green.
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
