---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-app
spec:
 # type: LoadBalancer
 #type: NodePort
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
